/**
 * This is the object class for a user.
 */
package edu.uga.cs.rideshare;

import java.util.List;

public class User {
    private String userId; //unique key generated by the database when user is added for the first time
    private String userEmail; //email user used to register
    private int points; //user's total points
    private RideOffer rideOffers; //ride offers created by user
    private RideRequest rideRequests; //ride requests created by user
    private RideOffer acceptedRideOffers; //offers accepted by user
    private RideRequest acceptedRideRequests; //requests accepted by user

    //default constructor
    public User()
    {
        this.userId = null;
        this.userEmail = null;
        this.points = 0;
        this.rideOffers = null;
        this.rideRequests = null;
        this.acceptedRideOffers = null;
        this.acceptedRideRequests = null;
    }

    //constructor
    public User( String userId, String userEmail, int points, RideOffer rideOffers, RideRequest rideRequests, RideOffer acceptedRideOffers, RideRequest acceptedRideRequests) {
        this.userId = userId;
        this.userEmail = userEmail;
        this.points = points;
        this.rideOffers = rideOffers;
        this.rideRequests = rideRequests;
        this.acceptedRideOffers = acceptedRideOffers;
        this.acceptedRideRequests = acceptedRideRequests;
    }

    //get and set methods for variables
    public String getUserId() { return userId; }

    public void setUserId(String userId) { this.userId = userId; }

    public String getUserEmail() { return userEmail; }

    public void setUserEmail(String userEmail) { this.userEmail = userEmail; }

    public int getPoints() { return points; }

    public void setPoints(int points) { this.points = points; }

    public RideOffer getRideOffers() { return rideOffers; }

    public void setRideOffers(RideOffer rideOffers) { this.rideOffers = rideOffers; }

    public RideRequest getRideRequests() { return rideRequests; }

    public void setRideRequests(RideRequest rideRequests) { this.rideRequests = rideRequests; }

    public RideOffer getAcceptedRideOffers() { return acceptedRideOffers; }

    public void setAcceptedRideOffers(RideOffer acceptedRideOffers) { this.acceptedRideOffers = acceptedRideOffers; }

    public RideRequest getAcceptedRideRequests() { return acceptedRideRequests; }

    public void setAcceptedRideRequests(RideRequest acceptedRideRequests) { this.acceptedRideRequests = acceptedRideRequests; }
}
